LineLength:
  Enabled: true
  Max: 129
SpaceAroundBraces:
  Enabled: false
StringLiterals:
  Enabled: false
NestedTernaryOperator:
  Enabled: false
HashSyntax:
  Enabled: false
AlignParameters:
  Enabled: false
Lambda:
  Enabled: false
ParenthesesAroundCondition:
  # this mostly just triggers on safe assignment
  Enabled: false
ParameterLists:
  # The default is 5, but we rarely have more than 4. Let's keep it that way.
  Max: 4
EndAlignment:
  Enabled: false
MethodLength:
  Max: 50
  CountComments: false
